version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "IMAGE_REPO_NAME=${IMAGE_REPO_NAME:-default_repo_name}"
      - echo "IMAGE_TAG=${IMAGE_TAG:-latest}"
      - export IMAGE_REPO_NAME=${IMAGE_REPO_NAME:-default_repo_name}
      - export IMAGE_TAG=${IMAGE_TAG:-latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "Running: docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} ."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo "Running: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
