version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - aws --version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --name my-eks-cluster --region us-west-2
      - mkdir -p $HOME/.kube
      - cp /root/.kube/config $HOME/.kube/config
      - export KUBECONFIG=$HOME/.kube/config
      - echo "KUBECONFIG contents:"
      - cat $KUBECONFIG
      - echo "Current kubectl context:"
      - kubectl config current-context
      - echo "All kubectl contexts:"
      - kubectl config get-contexts

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Deploying to EKS...
      - echo "Cluster info:"
      - kubectl cluster-info
      - echo "Attempting to get nodes:"
      - kubectl get nodes
      - echo "Attempting to get pods:"
      - kubectl get pods -A
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPOSITORY_URI:$IMAGE_TAG
      - kubectl rollout status deployment/$DEPLOYMENT_NAME

artifacts:
  files: []
